name: Push/Notify

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Check out repository ⭕
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Restore Gradle cache 💡
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Setup Java 17 🔨
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17
      - name: Grant execution permission to Gradle Wrapper 📜
        run: chmod +x gradlew
      - name: Build debug APK 💻
        run: ./gradlew assembleDebug
      - name: Sign debug APK 📝
        uses: r0adkll/sign-android-release@v1
        id: sign-debug-apk
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Rename artifact 🗃
        run: |
          oldArtifactPath="${{ steps.sign-debug-apk.outputs.signedReleaseFile }}"
          newArtifactPath="${oldArtifactPath%'-signed.apk'}.apk"
          echo "ARTIFACT_PATH=$newArtifactPath" >> $GITHUB_ENV
          mv "$oldArtifactPath" "$newArtifactPath"

      - name: Upload Files to Drive
  # You may pin to the exact commit or the version.
  # uses: intersecato/google-drive-uploader@9b85e8c08bbbab4c9220e01f69fa4f698e6d1646
        uses: intersecato/google-drive-uploader@1.0.0
        with:
    # Google Service Account credentials
          credentials: ${{secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS}}
    # Google Drive folder ID to upload the file/folder to
          folder: 18YGYYN4A8pR-MQGHWgjZTzr89dyF083y
    # Local path to the file/folder to upload
          target: ${{env.ARTIFACT_PATH}}
